### PR TITLE
Create inline contextual toolbar

### PR DESCRIPTION
**Pull request by phpbits**
### Description
Show contextual toolbar when text is selected inside the block.

### Screenshots
Screen Capture on 2020-05-31 at 19-01-01

### Limitations
Does not work on multi block selection, hence not being displayed.

### CODE REVIEW

**Comment by phpbits** [comment]
@richtabor  Added transform button for heading and quote blocks.

Screen Shot 2020-06-02 at 6 44 21 PM

**Comment by phpbits** [comment]
@richtabor Added image alignment toolbar as well :) Just need your touch with toolbar and alignment styling.

Screen Shot 2020-06-03 at 8 38 48 AM

**Comment by phpbits** [comment]
Added "Image Settings" for alt, size and link options as well 👍 

Screen Capture on 2020-06-03 at 19-56-20

**Comment by richtabor** [comment]
Good stuff! Couple thoughts: 

1. We should add an editor setting (default to `true`) to enable/disable this. The label should be `Contextual inline toolbars`.
Screen Shot 2020-06-14 at 8 42 42 PM

2. I like the idea of including the Header and Quote transforms, however they perform different than the other contextual controls. Where "bold" will bold the selected text, the transform controls will manipulate the entire content to morph into a header, instead of just the selected text. I think that's a bit confusing and I'd say we should remove Heading and Quote transforms (for now at least). _(I've done this in my recent commit)._

3. I've updated the PR to use editor theme colors as below, what do you think? 
Screen Shot 2020-06-14 at 8 40 27 PM
Screen Shot 2020-06-14 at 8 40 54 PM
Screen Shot 2020-06-14 at 8 41 06 PM

**Comment by phpbits** [comment]
@richtabor Done with the changes and removed the media toolbar for now. Could you try it out without the Gutenberg plugin? The styling seems a bit off. Thanks!

**Comment by richtabor** [comment]
Fixed :)

**Comment by phpbits** [comment]
@richtabor Revisiting this one for the image toolbar. I think it's a pretty neat feature to have, specially setting up the image alt text ;)

**Pull request merged**
